### ISSUE TITLE
#send

### ISSUE THREAD

**Issue by terrellt** [psyho/bogus#66]
Should calls to #send(:method, args) be recorded as if you called .method(args), for purposes of verifying contracts? Trying to de-duplicate some common accessor code, and I can't do it without eval.

**Comment by psyho** [comment]
This one is a bit tricky, because `send` is pretty often overwritten (as in `message.send`). Double recording sends will pollute the interaction list and probably sometimes lead to incorrect results.

An alternative (which already works) is to use `__send__` instead of `send` in your code. It's a bit more verbose, but it's pretty much never overwritten (and I would consider it a very bad practice to overwrite that method) and the `__send__` calls are recorded exactly as you'd expect.

**Comment by terrellt** [comment]
@psyho That solves my problems. :)
